language: node_js

node_js:
  - 18

before_script:
  - npm install

before_deploy:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/jokery
  on:
    branch: main
